# Generated by Django 5.1.7 on 2025-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('job_role', models.CharField(blank=True, choices=[('AI Engineer', 'AI Engineer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Scientist', 'Data Scientist'), ('Product Manager', 'Product Manager')], default='Not Specified', max_length=50, null=True)),
                ('availability', models.DateField(blank=True, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('resume_id', models.CharField(blank=True, max_length=255, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('digital_marketing', 'Digital Marketing'), ('ui_ux', 'UI/UX Design'), ('seo', 'SEO Services'), ('other', 'Other')], max_length=50)),
                ('project_scope', models.CharField(choices=[('small', 'Small Project'), ('medium', 'Medium Project'), ('large', 'Large Scale Project')], max_length=50)),
                ('employees_count', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('200+', 'More than 200')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='service_requests/documents/')),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
