# Generated by Django 3.1.12 on 2025-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('digital_marketing', 'Digital Marketing'), ('ui_ux', 'UI/UX Design'), ('seo', 'SEO Services'), ('other', 'Other')], max_length=50)),
                ('project_scope', models.CharField(choices=[('small', 'Small Project'), ('medium', 'Medium Project'), ('large', 'Large Scale Project')], max_length=50)),
                ('employees_count', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('200+', 'More than 200')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
