# Generated by Django 3.1.12 on 2025-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250321_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_id',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
