# Generated by Django 3.1.12 on 2025-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250321_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
