# Generated by Django 3.1.12 on 2025-03-21 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250322_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='address',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='country',
            field=models.TextField(default='India'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='availability',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_role',
            field=models.CharField(choices=[('AI Engineer', 'AI Engineer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Scientist', 'Data Scientist'), ('Product Manager', 'Product Manager')], default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='preferred_location',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='resume/raj.pdf', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='company',
            field=models.CharField(default='xyz', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
