# Generated by Django 3.1.12 on 2025-03-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250322_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='country',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
